(async function(){
  'use strict';var jobs=[],current=null,busy=false,stop=false,ready=false;var $=function(id){return document.getElementById('scan-'+id);};
  var labels={waiting:'Chưa quét',analyzing:'AI đang nhận dạng',rendering:'Đang render',real:'Thực tế · đã render',basic:'Toán cơ bản · loại khỏi kho thực tế',error:'Lỗi nhận dạng',renderError:'Thực tế · render lỗi',edited:'Mã đã sửa · cần render',saved:'Đã lưu Drive'};
  function node(tag,cls,text){var e=document.createElement(tag);if(cls)e.className=cls;if(text)e.textContent=text;return e;}
  function eligible(j){return j.result&&j.result.isReal&&j.image&&j.builtSource===j.item.source&&j.item.title.trim()&&!j.saved;}
  function progress(){var processed=jobs.filter(function(j){return j.result;}).length,real=jobs.filter(function(j){return j.result&&j.result.isReal;}).length,chosen=jobs.filter(function(j){return j.chosen&&eligible(j);}).length;$('progress').textContent=jobs.length+' hình · '+processed+' đã nhận dạng · '+real+' thực tế · '+chosen+' chọn lưu';$('meter').max=Math.max(1,jobs.length);$('meter').value=processed;$('save').disabled=busy||!chosen||API.chayThu;$('start').disabled=busy||!jobs.some(function(j){return !j.saved&&['waiting','error','renderError','edited'].indexOf(j.status)>=0;})||!ready;$('stop').disabled=!busy;$('files').disabled=$('folder').disabled=$('add').disabled=busy;}
  function queue(){var out=$('queue-list'),filter=$('filter').value;out.replaceChildren();jobs.filter(function(j){return filter==='all'||filter==='chosen'&&j.chosen||filter==='real'&&(!j.result||j.result.isReal);}).forEach(function(j){var b=node('button','scan-job'+(j===current?' bat':'')),name=node('strong','',j.item.title||j.file),state=node('span','mo',labels[j.status]),origin=node('span','mo',j.file+' · Hình '+j.number+(j.chosen?' · ✓ Chọn lưu':''));b.type='button';b.append(name,state,origin);b.onclick=function(){if(busy)return;current=j;detail();queue();};out.append(b);});if(!out.children.length)out.append(node('p','phu','Không có hình phù hợp bộ lọc.'));progress();}
  function preview(){var out=$('preview');out.replaceChildren();if(current&&current.image&&current.builtSource===current.item.source){var img=node('img');img.src=current.image;img.alt=current.item.title||'Hình TikZ';out.append(img);}else out.textContent=current&&current.buildError||'Chưa có ảnh cho mã hiện tại.';}
  function detail(){var j=current;$('empty').hidden=!!j;$('detail').hidden=!j;if(!j)return;$('origin').textContent=j.file+' · Hình '+j.number;$('original').textContent=j.original;
    $('verdict').textContent=j.result?(j.result.isReal?'HÌNH THỰC TẾ':'HÌNH TOÁN CƠ BẢN')+' · AI tự đánh giá '+Math.round(j.result.confidence*100)+'%':'CHƯA NHẬN DẠNG · MÃ GỐC';
    $('reason').textContent=j.error||j.result&&j.result.reason||'Bấm Quét AI và render để phân loại hình.';
    $('removed').textContent=j.result&&j.result.removed.length?'Đã tách: '+j.result.removed.join(' · '):'';
    ['title','grade','topic','tags','description','source'].forEach(function(k){$(k).value=j.item[k]||'';$(k).disabled=busy||j.saved;});$('chosen').checked=!!j.chosen;$('chosen').disabled=busy||!eligible(j);
    $('one').disabled=busy||!ready||j.saved;$('build').disabled=busy||!j.item.source||j.saved;$('draft').disabled=busy||!j.item.source;$('tex').disabled=busy||!j.item.source;preview();
  }
  function lock(value){busy=value;if(!value)$('stop').textContent='Dừng sau hình này';progress();detail();}
  function add(text,name){var parsed=QuetTikz.split(text,name);if(jobs.length+parsed.length>300)throw Error('Một phiên tối đa 300 hình. Chia kho thành nhiều đợt.');parsed.forEach(function(p){var item=Tikz.moi();item.title=p.file.replace(/\.tex$/i,'')+' · Hình '+p.number;item.source=p.original;jobs.push(Object.assign(p,{id:item.id,item:item,status:'waiting',image:'',builtSource:'',chosen:false}));});current=current||jobs[0];detail();queue();}
  async function files(input){if(busy)return;var picked=Array.from(input.files||[]).filter(function(f){return /\.tex$/i.test(f.name);});if(!picked.length){HienThi.loi(Error('Chọn ít nhất một file .tex.'));return;}HienThi.xoaLoi();var errors=[];for(var f of picked){try{if(f.size>2000000)throw Error('File vượt 2 MB.');add(await f.text(),f.webkitRelativePath||f.name);}catch(e){errors.push(f.name+': '+e.message);}}input.value='';if(errors.length)HienThi.loi(Error(errors.join('\n')));}
  $('files').onchange=function(){files(this);};$('folder').onchange=function(){files(this);};$('add').onclick=function(){HienThi.xoaLoi();try{add($('paste').value,'Mã đã dán');$('paste').value='';}catch(e){HienThi.loi(e);}};$('filter').onchange=queue;
  async function render(j){j.status='rendering';j.image='';j.builtSource='';j.buildError='';current=j;detail();queue();try{j.image=await Kho.build(j.item.source);j.builtSource=j.item.source;j.status=j.result&&j.result.isReal?'real':'waiting';}catch(e){j.status=j.result?'renderError':'waiting';j.buildError=e.message;}detail();queue();}
  async function analyze(j){j.status='analyzing';j.error='';j.buildError='';j.chosen=false;j.image='';j.builtSource='';current=j;detail();queue();
    try{var result=(await Kho.api('quetHinh',{file:j.file,source:j.original,context:j.context})).result;j.result=result;if(result.isReal){j.item=Object.assign(j.item,result.item);await render(j);}else{j.status='basic';j.item.source='';} }
    catch(e){j.status='error';j.error=e.message;}detail();queue();
  }
  $('start').onclick=async function(){if(busy||!ready)return;stop=false;lock(true);HienThi.xoaLoi();var pending=jobs.filter(function(j){return !j.saved&&['waiting','error','renderError','edited'].indexOf(j.status)>=0;});
    try{for(var j of pending){if(stop)break;if(j.result&&j.result.isReal)await render(j);else await analyze(j);if(j.status==='error'&&/API key|kết nối|máy chủ|hạn mức|nhiều yêu cầu/i.test(j.error)){HienThi.loi(Error(j.error));break;}}}finally{if($('filter').value==='real'&&current&&current.result&&!current.result.isReal)current=jobs.find(function(j){return j.result&&j.result.isReal;})||current;lock(false);queue();}
  };
  $('stop').onclick=function(){stop=true;this.disabled=true;this.textContent='Đang chờ dừng…';};
  $('one').onclick=async function(){if(busy||!current||!ready)return;lock(true);try{await analyze(current);}finally{lock(false);queue();}};
  $('build').onclick=async function(){if(busy||!current)return;lock(true);try{await render(current);}finally{lock(false);queue();}};
  ['title','grade','topic','tags','description','source'].forEach(function(k){$(k).oninput=function(){if(!current||busy||current.saved)return;current.drafted=false;current.item[k]=this.value;if(k==='source'){current.status='edited';current.image='';current.builtSource='';current.chosen=false;preview();}if(k==='source'||k==='title'){$('chosen').disabled=!eligible(current);if(!eligible(current)){current.chosen=false;$('chosen').checked=false;}}queue();};});
  $('chosen').onchange=function(){if(current)current.chosen=this.checked&&eligible(current);queue();};
  $('draft').onclick=async function(){if(!current||busy)return;try{var draft=Object.assign({},current.item,{id:'nhap-'+current.id,image:current.image,imageSource:current.builtSource});await Kho.nhap(draft);current.drafted=true;GiaoDien.thongBao('Đã lưu nháp. Mở Dữ liệu Hình TikZ để sửa tiếp.');}catch(e){HienThi.loi(e);}};
  $('tex').onclick=function(){if(current)Kho.tai(current.item.source,Tikz.ten(current.item.title,current.id)+'.tex','text/plain;charset=utf-8');};
  $('save').onclick=async function(){if(busy||API.chayThu)return;var chosen=jobs.filter(function(j){return j.chosen&&eligible(j);});if(!chosen.length)return;stop=false;lock(true);HienThi.xoaLoi();var errors=[];
    try{for(var j of chosen){if(stop)break;try{j.item=await Kho.luu(Object.assign({},j.item,{kind:'real',image:j.image,imageSource:j.builtSource}));j.saved=true;j.chosen=false;j.status='saved';}catch(e){errors.push(j.item.title+': '+e.message);}current=j;detail();queue();}if(errors.length)HienThi.loi(Error(errors.join('\n')));else GiaoDien.thongBao('Đã lưu các hình được chọn vào kho Drive.');}finally{lock(false);queue();}
  };
  window.addEventListener('beforeunload',function(e){if(busy||jobs.some(function(j){return j.result&&j.result.isReal&&!j.saved&&!j.drafted;})){e.preventDefault();e.returnValue='';}});
  try{var config=await AIUI.read(),c=config.providers[config.active];ready=!API.chayThu&&c.hasKey;var provider=(AIUI.catalog[config.active]||{name:config.active}).name;$('ai-state').textContent=provider+(ready?' · Sẵn sàng':' · Chưa kết nối API');$('ai-state').title=c.model+(ready?'':' · Kết nối Apps Script và lưu API key trong Cài đặt.');}catch(e){HienThi.loi(e);}queue();
})();
