(async function(){
  'use strict';var item=Tikz.moi(),image='',builtSource='',busy=false,dirty=false;var fields=['title','kind','grade','topic','tags','description','source'],params=new URLSearchParams(location.search);
  function fill(){fields.forEach(function(k){document.getElementById(k).value=item[k]||'';});image=item.image||'';builtSource=item.imageSource||'';paint();}
  function collect(){fields.forEach(function(k){item[k]=document.getElementById(k).value;});return item;}
  function paint(){var preview=document.getElementById('preview'),valid=image&&builtSource===document.getElementById('source').value;preview.replaceChildren();if(valid){var img=document.createElement('img');img.src=image;img.alt=item.title||'Hình TikZ';preview.append(img);}else preview.textContent='Bấm Build hình hoặc F5 để xem mã hiện tại.';document.getElementById('anh').disabled=!valid;document.getElementById('anh-trang-thai').textContent=valid?'Ảnh hiện tại':'Chưa build mã hiện tại';}
  function lock(value){busy=value;['build','luu','nhap','ai-sua','hoan-tac-ai'].forEach(function(id){document.getElementById(id).disabled=value;});document.getElementById('source').readOnly=value;}
  async function build(){if(busy)return;lock(true);HienThi.xoaLoi();var source=collect().source;document.getElementById('preview').textContent='Đang build hình…';try{image=await Kho.build(source);builtSource=source;dirty=true;paint();}catch(e){HienThi.loi(e);paint();}finally{lock(false);}}
  document.getElementById('build').onclick=build;var maTruocAI=null;async function aiSua(){if(busy)return;HienThi.xoaLoi();var source=collect().source,goc=source,loi='',daDoi=false;try{Tikz.tach(source);if(source.indexOf('\\documentclass')>=0)throw Error('Chỉ nhập mã hình tikzpicture; macro đặt trong phần Cài đặt.');}catch(e){HienThi.loi(e);return;}lock(true);var hien=document.getElementById('preview');try{for(var lan=1;lan<=2;lan++){hien.textContent='AI đang đọc lỗi và sửa mã… (lần '+lan+'/2, có thể mất 1–2 phút)';var kq=await Kho.suaMa(source,loi);if(kq.khongLoi){if(kq.image){image=kq.image;builtSource=source;}GiaoDien.thongBao(lan===1?'Mã đang build được, không có lỗi để AI sửa.':'Mã đã build được.');break;}if(!daDoi){maTruocAI=goc;daDoi=true;}source=kq.source;document.getElementById('source').value=source;dirty=true;document.getElementById('trang-thai').textContent='Có thay đổi chưa lưu';if(kq.daBuild){image=kq.image;builtSource=source;GiaoDien.thongBao('AI đã sửa xong, hình build thành công. Hãy xem lại trước khi lưu.');break;}loi=kq.loiBuild||'';if(lan===2)throw Error('AI đã sửa 2 lần nhưng mã vẫn chưa build được. Lỗi còn lại:\n'+loi.slice(0,1500)+'\n\nMã AI sửa đang để trong khung. Bấm "AI sửa mã" để thử tiếp, hoặc "Khôi phục mã trước khi AI sửa".');}}catch(e){HienThi.loi(e);}finally{lock(false);document.getElementById('hoan-tac-ai').hidden=maTruocAI===null;paint();}}document.getElementById('ai-sua').onclick=aiSua;document.getElementById('hoan-tac-ai').onclick=function(){if(busy||maTruocAI===null)return;document.getElementById('source').value=maTruocAI;maTruocAI=null;this.hidden=true;dirty=true;document.getElementById('trang-thai').textContent='Có thay đổi chưa lưu';paint();GiaoDien.thongBao('Đã khôi phục mã trước khi AI sửa.');};window.addEventListener('keydown',function(e){if(e.key==='F5'){e.preventDefault();if(!viewer)build();}});
  fields.forEach(function(k){document.getElementById(k).addEventListener('input',function(){dirty=true;document.getElementById('trang-thai').textContent='Có thay đổi chưa lưu';if(k==='source')paint();});});
  async function save(toDrive){if(busy)return;HienThi.xoaLoi();try{collect();if(!item.title.trim())throw Error('Nhập tên hình trước khi lưu.');Tikz.tach(item.source);if(item.source.indexOf('\\documentclass')>=0)throw Error('Chỉ lưu mã hình tikzpicture.');if(item.kind==='basic'&&!item.grade)throw Error('Chọn khối lớp cho hình toán cơ bản.');if(toDrive&&(!image||builtSource!==item.source))throw Error('Build lại mã hiện tại trước khi lưu Drive.');lock(true);item.image=builtSource===item.source?image:'';item.imageSource=item.image?builtSource:'';item.updatedAt=new Date().toISOString();if(toDrive){item=await Kho.luu(item);dirty=false;document.getElementById('trang-thai').textContent='Đã lưu vào Drive';history.replaceState(null,'','them-mau.html?id='+encodeURIComponent(item.id));}else{var draft=Object.assign({},item,{id:item.id.indexOf('nhap-')===0?item.id:'nhap-'+item.id,driveId:item.driveId||item.id.replace(/^nhap-/,'')});await Kho.nhap(draft);if(API.chayThu)item=draft;dirty=false;document.getElementById('trang-thai').textContent='Đã lưu nháp trên máy';}GiaoDien.thongBao(toDrive?'Đã lưu mã và ảnh trên Drive.':'Đã lưu bản nháp trên máy.');}catch(e){HienThi.loi(e);}finally{lock(false);}}
  document.getElementById('luu').onclick=function(){save(true);};document.getElementById('nhap').onclick=function(){save(false);};
  document.getElementById('copy').onclick=async function(){try{await navigator.clipboard.writeText(document.getElementById('source').value);GiaoDien.thongBao('Đã copy mã.');}catch(e){HienThi.loi(Error('Hãy chọn mã và sao chép thủ công.'));}};
  document.getElementById('tex').onclick=function(){collect();Kho.tai(item.source,Tikz.ten(item.title,item.id)+'.tex','text/plain;charset=utf-8');};document.getElementById('anh').onclick=async function(){var blob=await(await fetch(image)).blob();var ext={'image/png':'png','image/svg+xml':'svg','image/jpeg':'jpg','image/webp':'webp'}[blob.type]||'png';Kho.tai(blob,Tikz.ten(item.title,item.id)+'.'+ext,blob.type);};
  document.getElementById('tep').onchange=async function(e){var file=e.target.files[0];if(!file)return;try{if(file.size>300000)throw Error('File tối đa 300 KB.');var text=await file.text();item.source=Tikz.tach(text);item.title=item.title||file.name.replace(/\.tex$/i,'');fill();dirty=true;if(text.indexOf('\\documentclass')>=0)GiaoDien.thongBao('Đã lấy mã hình; thêm các macro cần thiết trong Cài đặt.');}catch(e){HienThi.loi(e);}e.target.value='';};
  var viewer=DangNhap.phien()&&DangNhap.phien().vaiTro==='hocsinh';if(viewer){['build','nhap','luu','ai-sua'].forEach(function(id){document.getElementById(id).hidden=true;});fields.forEach(function(k){var el=document.getElementById(k);if(el.tagName==='SELECT')el.disabled=true;else el.readOnly=true;});document.getElementById('tep').disabled=true;}
  var canSave=API.chayThu||DangNhap.phien()&&DangNhap.phien().vaiTro==='admin';if(!canSave){document.getElementById('luu').hidden=true;}else if(API.chayThu)document.getElementById('luu').title='Cần nối Apps Script để lưu Drive';
  window.addEventListener('beforeunload',function(e){if(dirty){e.preventDefault();e.returnValue='';}});
  try{if(params.get('id')){item=await Kho.doc(params.get('id'));document.getElementById('tieu-de').textContent='Chỉnh sửa mẫu';}else if(params.get('tao')){item=await Kho.docNhap(params.get('tao'));if(!item)throw Error('Không tìm thấy hình vừa tạo.');dirty=true;}if(params.get('loai')==='real')item.kind='real';fill();}catch(e){HienThi.loi(e);fill();}
})();

