(async function(){
  'use strict';var items=[],selected=new Set();var out=document.getElementById('ket-qua');
  function render(list){out.replaceChildren();if(!list.length){out.innerHTML='<p>Chưa tìm được mẫu. Thử tìm theo tên hoặc bổ sung mẫu vào kho.</p>';return;}list.forEach(function(item){var label=document.createElement('label');label.className='lua-chon';var checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=selected.has(item.id);checkbox.disabled=!checkbox.checked&&selected.size>=3;var content=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('p');title.textContent=item.title;detail.className='mo';detail.textContent=(item.kind==='real'?'Thực tế':'Toán cơ bản')+(item.grade?' · Khối '+item.grade:'');content.append(title,detail);label.append(checkbox,content);checkbox.onchange=function(){if(checkbox.checked)selected.add(item.id);else selected.delete(item.id);show();render(list);};out.append(label);});}
  function show(){document.getElementById('da-chon').textContent=selected.size+' / 3 mẫu đã chọn';document.getElementById('ve').disabled=!selected.size;}
  document.getElementById('tim-mau').onclick=function(){selected.clear();show();render(Tikz.tim(items,document.getElementById('de').value));};document.getElementById('tim-ten').oninput=function(e){var q=Tikz.chuan(e.target.value);render(items.filter(function(x){return Tikz.chuan(x.title+' '+x.tags+' '+x.topic).indexOf(q)>=0;}).slice(0,30));};
  document.getElementById('ve').onclick=async function(){var b=this;b.disabled=true;b.textContent='Đang đọc mẫu và tạo mã…';HienThi.xoaLoi();try{var prompt=document.getElementById('de').value;if(!prompt.trim())throw Error('Nhập đề bài trước.');var source=await Kho.ve(prompt,Array.from(selected));var first=items.find(function(x){return selected.has(x.id);}),draft=Object.assign(Tikz.moi(),{source:Tikz.tach(source),title:prompt.slice(0,80),description:prompt,kind:first.kind,grade:first.grade,topic:first.topic});draft.id='nhap-'+draft.id;await Kho.nhap(draft);location.href='them-mau.html?tao='+encodeURIComponent(draft.id);}catch(e){HienThi.loi(e);}finally{b.disabled=!selected.size;b.textContent='Tạo mã hình';}};
  try{items=(await Kho.danhSach()).filter(function(x){return API.chayThu || x.id.indexOf('nhap-')!==0;});}catch(e){HienThi.loi(e);}
})();

