(function(){
  'use strict';var promise;
  function db(){if(!promise)promise=new Promise(function(ok,no){var r=indexedDB.open('mathtikz-static',1);r.onupgradeneeded=function(){r.result.createObjectStore('samples',{keyPath:'id'});};r.onsuccess=function(){ok(r.result);};r.onerror=function(){no(r.error);};});return promise;}
  function read(id){return db().then(function(d){return new Promise(function(ok,no){var r=d.transaction('samples').objectStore('samples')[id?'get':'getAll'](id);r.onsuccess=function(){ok(r.result);};r.onerror=function(){no(r.error);};});});}
  function put(item){return db().then(function(d){return new Promise(function(ok,no){var t=d.transaction('samples','readwrite');t.objectStore('samples').put(item);t.oncomplete=function(){ok(item);};t.onerror=function(){no(t.error);};t.onabort=function(){no(t.error||Error('Không lưu được bản nháp.'));};});});}
  async function api(action,data){var result=await API.goi(action,data);if(!result||!result.ok)throw Error(result&&result.loi||'Không nhận được dữ liệu.');return result;}
  async function danhSach(){if(API.chayThu)return read();var remote=(await api('dsHinh')).items;var drafts=await read();return drafts.concat(remote);}
  async function doc(id){if(id.indexOf('nhap-')===0 || API.chayThu){var local=await read(id);if(!local)throw Error('Không tìm thấy bản nháp trên máy.');return local;}return (await api('docHinh',{id:id})).item;}
  async function build(source){var pure=Tikz.tach(source);if(source.indexOf('\\documentclass')>=0)throw Error('Chỉ nhập mã hình; đặt macro trong phần Cài đặt.');if(!API.chayThu)return (await api('buildHinh',{source:pure})).image;
    var macro=localStorage.getItem('mtkweb_macro')||'';var r=await fetch(CAU_HINH.BUILD_TIKZ_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({source:Tikz.boc(pure,macro)}),signal:AbortSignal.timeout(95000)});if(!r.ok)throw Error('Build lỗi ('+r.status+'): '+(await r.text()).slice(0,1500));
    var type=r.headers.get('content-type')||'';if(type.indexOf('json')>=0){var d=await r.json();var b=d.base64||d.image||d.image_base64||d.png||d.png_base64||d.result&&d.result.base64||d.output&&d.output.base64;if(!b||typeof b!=='string')throw Error('API chưa trả ảnh.');return b.indexOf('data:image/')===0?b:'data:image/png;base64,'+b;}
    var blob=await r.blob();if(blob.type.indexOf('image/')!==0)throw Error('API chưa trả định dạng ảnh hợp lệ.');return new Promise(function(ok,no){var f=new FileReader();f.onload=function(){ok(f.result);};f.onerror=no;f.readAsDataURL(blob);});
  }
  window.Kho={api:api,danhSach:danhSach,doc:doc,build:build,nhap:put,docNhap:read,luu:async function(item){if(API.chayThu)throw Error('Chưa nối Apps Script. Bạn có thể lưu nháp trên máy.');var payload=Object.assign({},item,{id:item.driveId||String(item.id).replace(/^nhap-/,'')});return(await api('luuHinh',{item:payload})).item;},anh:async function(item){if(item.image)return item.image;if(API.chayThu||item.id.indexOf('nhap-')===0)return '';return(await api('anhHinh',{id:item.id})).image;},ve:async function(prompt,ids){if(API.chayThu)throw Error('Chức năng AI cần nối Apps Script và lưu API key trong Cài đặt API.');return(await api('veTheoDe',{prompt:prompt,ids:ids})).source;},suaMa:async function(source,loi){if(API.chayThu)throw Error('Chức năng AI cần nối Apps Script và lưu API key trong Cài đặt.');var r=await API.goi('suaMaAI',{source:source,loi:loi||''},290000);if(!r||!r.ok){var m=r&&r.loi||'Không nhận được dữ liệu.';if(/Hành động không hợp lệ/.test(m))m='Máy chủ Apps Script chưa có lệnh AI sửa mã. Cần dán tệp SuaMa.gs, thêm dòng case suaMaAI và triển khai phiên bản mới.';else if(r&&r.mang)m='Không nhận được phản hồi từ máy chủ (mạng chậm hoặc AI xử lý quá lâu). Bấm lại sau ít phút.';throw Error(m);}return r;},tai:function(content,name,type){var url=URL.createObjectURL(new Blob([content],{type:type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},3000);}};
})();
